alias: Water heater timer
description: Starts boiler, waits for 125°F or a 15m timeout, then runs recirc pump
triggers:
  - trigger: state
    entity_id: switch.hvac_water_heater
    from: "off"
    to: "on"
conditions: []
actions:
  - action: switch.turn_on
    target:
      entity_id:
        - switch.hvac_water_heater
        - switch.rear_driver_side_relay_board_fresh_water_pump
  - wait_for_trigger:
      - trigger: numeric_state
        entity_id: sensor.ac_control_boiler_supply_temperature
        above: 125
    timeout:
      minutes: 15
    continue_on_timeout: true
  - delay: "00:01:00"
  - action: switch.turn_on
    target:
      entity_id: switch.hvac_hot_water_recirc_control
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - action: switch.turn_off
    target:
      entity_id: switch.hvac_hot_water_recirc_control
  - delay: "00:15:00"
  - action: switch.turn_off
    target:
      entity_id:
        - switch.hvac_water_heater
        - switch.rear_driver_side_relay_board_fresh_water_pump
mode: restart
